### ISSUE TITLE
Rudder Pedal Interface Plate - Holes for eccentric nuts

### ISSUE THREAD

**Issue by dnamaster2000** [jrsteensen/OpenHornet#221] opened 2020-06-13 00:17 UTC
The holes for the eccentric nuts are not the proper size for the nuts selected. they are only used as spacers in the current arrangement. 
![image](https://user-images.githubusercontent.com/56710225/84555213-c030c300-ace9-11ea-9b76-e82e9eebf8d6.png)

**Comment by jrsteensen** [comment] 2020-06-13 15:04
Did you make the holes counterbored? (They should show as counterbored holes in the model.)

**Comment by dnamaster2000** [comment] 2020-06-13 15:22
Part was 3D printed, the through hole is M5 diamater, and the nuts sit in the counterbore, but doesn't provide any adjustment, the hole should be a through hole, with the diameter of the eccentric nut base, so that when the nut is rotated, it effectively moves the center, allowing the spacing (tension) of the wheel to be adjusted. good visuals here: https://www.youtube.com/watch?v=uMes1My5y5I

**Comment by jrsteensen** [comment] 2020-06-17 01:10
![image](https://user-images.githubusercontent.com/2449496/84843366-f2e9fc80-b004-11ea-8844-85d5e384002d.png)

I'm not totally sure how/why this doesn't work? The bore is constrained with a counterbore on bottom to allow it to turn at the correct height to ensure V-Wheel/Rail engagement, and a counterbore on the top for the SHCS.

**Comment by dnamaster2000** [comment] 2020-06-17 01:35
it looks/sounds like the eccentric nuts are not being used to adjust the position of the wheel, if that's the case, these wheels should be setup the same way as the opposing ones, using just a spacer.

**Comment by jrsteensen** [comment] 2020-06-17 01:40
No, if installed as shown, with the correct barbell shaped counterbore, it will adjust the position of the wheel horizontally. If the issue is the adjustment hex is interfering with the plate, we can open up the bottom counterbore to eliminate the interference.

**Comment by jrsteensen** [comment] 2020-06-17 02:10
....I'm an idiot.

Before: 
![image](https://user-images.githubusercontent.com/2449496/84846186-7d355f00-b00b-11ea-9d97-7a6bf9119b37.png)

After:
![image](https://user-images.githubusercontent.com/2449496/84847060-6f80d900-b00d-11ea-8a33-deeccd2042ff.png)

**Comment by jrsteensen** [comment] 2020-06-17 02:27
Closed in  1821ed0.

**Closed by jrsteensen** 2020-06-17 02:27 UTC
Labels: Category: MCAD, Priority: High, Status: Available, Type: Bug
