### ISSUE TITLE
[Bug]: Change the ACRL_.1875_OH1A8A1-115_UFC INNER SPACER PLATE_-_v30 files

### ISSUE THREAD

**Issue by Fedhi216** [jrsteensen/OpenHornet#824] opened 2023-05-18 12:07 UTC
### Discord Username

@Fedhi ²  = -1#7186

### Bug Summary

ACRL_.1875_OH1A8A1-115_UFC INNER SPACER PLATE_-_v30 the file is not updated 

### Expected Results

Change the file with the new one

### Actual Results

ACRL_.1875_OH1A8A1-115_UFC INNER SPACER PLATE_-_v30 the file is not updated in "OpenHornet\release\OH1_Upper_Instrument_Panel\OH1A8 - ASSY, UPFRONT CONTROL PANEL\Manufacturing"

### Screenshots/Images/Files

![ACRL_ 1875_OH1A8A1-115_UFC INNER SPACER PLATE_-_v30](https://github.com/jrsteensen/OpenHornet/assets/113025373/4c103ff4-490e-42c1-a730-8b6716554a48)

### Applicable Part Numbers

OH1A8A1-115

### Release Version

1.0.0-beta.1

### Category

Artwork (Decals)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [ ] I built (or attempted to build) the part to the OpenHornet print without any deviations.

**Comment by jrsteensen** [comment] 2023-05-18 18:18
Duplicate of #743

**Closed by jrsteensen** 2023-05-18 18:18 UTC
Labels: Type: Bug/Obsolesce, Type: Documentation, Deposition: Duplicate, Category: MCAD
